# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 84a7cb4721a6f8a8d7a689c2b3c9b3d9d6bbe6c51b94dac81d44fc9bba830262d12e05cdd83ea411889694e7b95fdc6846cb4220f72a1c20ee9c96576d6dffa1

test:
  secret_key_base: 536cdb8beeff538e62b814ea2d36f190d470fec90e0ef97b0ac80bc6bea25a6b4214b12351b45c04574faafd6122fda92402bfec2922ccc88ea647f4f8165690

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
